---
name: Release
run-name: Release Ansible Galaxy Collection
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Ansible Publish Linux/UNIX
      uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: "${ANSIBLE_GALAXY_API_KEY}"
        src_path: "images/capi/ansible/"
    - name: Ansible Publish Windows
      uses: ansible/ansible-publish-action@v1.0.0
      with:
        api_key: "${ANSIBLE_GALAXY_API_KEY}"
        src_path: "images/capi/ansible/windows/"